### ISSUE TITLE
Unable to get plugin to work

### ISSUE THREAD

**Issue by sgodkin** [Pretius/pretius-extend-classic-report#1]
Apex 5.1.1.00.08.  

1) Installed the Plugin
2) Created a dynamic action on a Classic Report region with Event <After Refresh>, Selection Type <Region> and Region <{My Region}>

3) Created a True action using Action <Pretius Extend> Freeze type <Columns> Columns to Freeze "1"

I've tried different approaches but always get the error
"1 error has occurred
Pretius Extend Classic Report [6980] : Number of columns to freeze is larger than number of all report columns"

Any thoughts on what I'm doing wrong?  Thx

**Comment by sypulabartosz** [comment]
Hi @sgodkin ,

Thanks, for your request, I made a small fix for raising this error message on the screen, when the query does not return any rows.

But when I was testing plugin on the Apex 5.1.1.00.08. I didn't find any wrong behavior in working of the plugin.

The thing which is crossing into my mind is that maybe you haven't used the standard template of the APEX region and report.

**Comment by sgodkin** [comment]
I created a new report, added an interactive report region with a simple query, added the dynamic action on the interactive report region.  It does not error but it also does not freeze the columns.  
The application was created by a consultant and I know they made changes to the applications themes and templates but I don't know what they changed and they left no documentation.  They must have changed something that is causing this to fail.  I'll have to find another way to do this.  Thank you very much for your quick response.   Awesome work!

**Comment by sypulabartosz** [comment]
The plugin is designed only for Classic Report that's why it's not working with Interactive Report. Thanks :)

**Comment by sgodkin** [comment]
Should have said I tried creating classic report first and had same result.
But thanks for your help.  I don't want to consume anymore of your time.

Thx,
Steve
    On Tuesday, October 27, 2020, 10:32:41 a.m. ADT, sypulabartosz <notifications@github.com> wrote:  
 
 


The plugin is designed only for Classic Report that's why it's not working with Interactive Report. Thanks :)
